### ISSUE TITLE
RTS reset issue

### ISSUE THREAD

**Issue by carrotIndustries** [msalau/rl78flash#5]
Not sure whether this is a bug in rl78flash or in the upd78f0730 kernel driver.
When using RTS for reset, as with the YRPBRL78L12 board,  the MCU is permanently reset, since idle level of the RTS line is 0V. When using the -r option, the MCU is only put into run mode for a very brief moment. By inserting a sleep(1) before closing the serial port, the MCU runs longer. When closing the port, the RTS line returns to idle level. I haven't found a stty option to change the idle level of the RTS line. Maybe this can be fixed by patching the kernel driver.

**Comment by msalau** [comment]
Hi,

The RTS line of upd78f0730 ICs is used solely for flashing and debugging. It should be physically disconnected to allow an MCU to run in free mode. This is stated in official Renesas guidelines for development boards.

The kernel module (driver) can't control behaviour of the converter after closing the port, because it sends the close command to the IC, and firmware of the IC decides what is the idle state of the RTS line.

There is a workaround for the issue: You can make use of the 'terminal' feature of rl78flash
(`-t <baud>` argument).

If you flash you MCU with command: `rl78flash -vivat 115200 /dev/ttyUSB0 firmware.mot`
(note the `-t 115200` argument).
rl78flash will flash `firmware.mot` and will open a terminal with requested baudrate to read debug messages from your MCU through the same UART0. Terminal will be open (and MCU will run) until You press Ctrl-C.

Maksim.
